#!/usr/bin/env bash
if [[ $# -eq 1 ]]; then
    selected=$1
else
    selected=$(find ~/projects ~/tests /mnt/d/.Cmd/Cmd/ /mnt/d/.Classes/Classes/CAndC++/ /mnt/d/.Classes/Classes/PythonCourse/ /mnt/d/.Classes/Classes/WebHtmlCss/ /mnt/d/.Classes/Classes/WebJavaScript/ /mnt/d/.Classes/Classes/ -mindepth 1 -maxdepth 1 -type d | fzf)
fi
if [[ -z $selected ]]; then
    exit 0
fi
selected_name=$(basename "$selected" | tr . _)
tmux_running=$(pgrep tmux)
if [[ -z $TMUX ]] && [[ -z $tmux_running ]]; then
    tmux new-session -s $selected_name -c $selected
    exit 0
fi
if ! tmux has-session -t=$selected_name 2> /dev/null; then
    tmux new-session -ds $selected_name -c $selected
fi
if [[ -z $TMUX ]]; then
    tmux attach -t $selected_name
else
    tmux switch-client -t $selected_name
fi

# Check if neovim is already running in the session
nvim_running=$(tmux list-panes -t $selected_name -F '#{pane_current_command}' | grep -i 'n\?vim')
if [[ -z $nvim_running ]]; then
    # Only launch neovim if it's not already running
    tmux send-keys -t $selected_name "nvim ." C-m
fi
